name: Update Subscribes

on:
  workflow_dispatch:
  schedule:
    - cron: '26 2 */3 * *'

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Load Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Setup Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Install Requirements
      run: |
        pip install -r requirements.txt
    - name: Update Subscribe
      run: |
        python main.py
    - name: commit
      uses: devops-infra/action-commit-push@master
      with:
        github_token: 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
        add_timestamp: true
        commit_prefix: "[AUTO]"
        commit_message: "Automatic commit"
        force: false
        target_branch: main
